version: '3.9'

services:

  client:
    build:
      context: client
      dockerfile: Dockerfile
    tty: true
    container_name: client
    ports:
      - "80:5000"
    depends_on:
      - server
    networks:
      - fullstack
    extra_hosts:
      - "host.docker.internal:host-gateway"

  server:
    build:
      context: server
      dockerfile: Dockerfile
    tty: true
    container_name: server
    ports:
      - "3001:3001"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
