version: '3.7'

services:

  client:
    image: client
    build:
      context: client
      dockerfile: Dockerfile
    tty: true
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - fullstack

  server:
    image: server
    build:
      context: server
      dockerfile: Dockerfile
    tty: true
    container_name: server
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
